CREATE TABLE IF NOT EXISTS company_value_added_service (
  company_id BIGINT NOT NULL PRIMARY KEY,
  freight_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  customs_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  crane_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  remark VARCHAR(500) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
